on:
  workflow_call:
    inputs:
      project:
        type: string
        required: true
        description: The Asana project to manipulate.
      merged-section:
        type: string
        required: true
        description: The name of the "merged" section in Asana.
      review-section:
        type: string
        required: true
        description: The name of the "in review" section in Asana.
    secrets:
      asana-token:
        required: true
      asana-github-secret:
        required: true
jobs:
  move-to-merged-asana-ticket-job:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]' &&  github.event.pull_request.merged == true
    steps:
      - name: Github-Asana action from Insurify
        uses: insurify/github-asana-action@v1.0.5
        with:
          asana-pat: ${{ secrets.asana-token }}
          trigger-phrase: "\\*\\*Asana Ticket:\\*\\*"
          targets: '[{"project": "${{ inputs.project }}", "section": "${{ inputs.merged-section }}"}]'
  move-to-in-review-asana-ticket-job:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]' && github.event.pull_request.merged != true
    steps:
      - name: Github-Asana action from Insurify
        uses: insurify/github-asana-action@v1.0.5
        with:
          asana-pat: ${{ secrets.asana-token }}
          trigger-phrase: "\\*\\*Asana Ticket:\\*\\*"
          targets: '[{"project": "${{ inputs.project }}", "section": "${{ inputs.review-section }}"}]'
  create-asana-attachment-job:
    runs-on: ubuntu-latest
    name: Create pull request attachments on Asana tasks
    if: github.actor != 'dependabot[bot]'
    steps:
      - name: Create pull request attachments
        uses: Asana/create-app-attachment-github-action@v1.2
        id: postAttachment
        with:
          asana-secret: ${{ secrets.asana-github-secret }}
      - name: Log output status
        run: echo "Status is ${{ steps.postAttachment.outputs.status }}"
