on:
  workflow_call:
    inputs:
      development-section:
        type: string
        required: false
        description: The Asana project section for tickets with PRs that are in development. Requires secrets.asana-token.
      review-section:
        type: string
        required: false
        description: The Asana project section for tickets with PRs that have a review requested. Requires secrets.asana-token.
      approved-section:
        type: string
        required: false
        description: The Asana project section for tickets with PRs that have been approved. Requires secrets.asana-token.
      merged-section:
        type: string
        required: false
        description: The Asana project section for tickets with PRs that have been merged. Requires secrets.asana-token.
      complete-on-merge:
        type: boolean
        default: false
        description: Whether to mark tasks for merged PRs as complete. Requires secrets.asana-token.
      attach-pr:
        type: boolean
        default: false
        description: Whether to attach the PR to the Asana ticket. Requires secrets.asana-github-secret.
      trigger-phrase:
        type: string
        default: "\\*\\*Asana Ticket:\\*\\*"
        description: Phrase to trigger moving ticket between columns.
    secrets:
      asana-token:
        required: false
        description: Asana personal access token that GitHub Actions uses to move ticket between sections.
      github-secret:
        required: false
        description: GitHub secret that Asana uses to fetch PR information.
jobs:
  check-for-secrets:
    runs-on: ubuntu-latest
    outputs:
      has-asana-token: ${{ steps.one.outputs.has-asana-token }}
      has-github-secret: ${{ steps.one.outputs.has-github-secret }}
    steps:
      - id: one
        run: |
          [ -n "${{ secrets.asana-token }}" ] && echo "has-asana-token=yes" >> "$GITHUB_OUTPUT"
          [ -n "${{ secrets.github-secret }}" ] && echo "has-github-secret=yes" >> "$GITHUB_OUTPUT"
          cat "$GITHUB_OUTPUT"
  move-to-in-development-asana-ticket-job:
    runs-on: ubuntu-latest
    needs: check-for-secrets
    if: inputs.development-section != '' && needs.check-for-secrets.outputs.has-asana-token == 'yes' && (github.event.action == 'submitted' && github.event.review.state == 'changes_requested') || (github.event.action == 'opened' || github.event.action == 'reopened' || github.event.action == 'converted_to_draft' || github.event.action == 'edited') && (toJson(github.event.pull_request.requested_reviewers) == '[]' && toJson(github.event.pull_request.requested_teams) == '[]' || github.event.pull_request.draft) && github.actor != 'dependabot[bot]'
    steps:
      - name: Move ticket to In Development
        uses: mbta/github-asana-action@v4.4.2
        with:
            asana-pat: ${{ secrets.asana-token }}
            trigger-phrase: ${{ inputs.trigger-phrase }}
            target-section: ${{ inputs.development-section }}
  move-to-merged-asana-ticket-job:
    runs-on: ubuntu-latest
    needs: check-for-secrets
    if: inputs.merged-section != '' && needs.check-for-secrets.outputs.has-asana-token == 'yes' && github.event.pull_request.merged == true && github.actor != 'dependabot[bot]'
    steps:
      - name: Move ticket on merge
        uses:  mbta/github-asana-action@v4.4.2
        with:
          asana-pat: ${{ secrets.asana-token }}
          trigger-phrase: ${{ inputs.trigger-phrase }}
          target-section: ${{ inputs.merged-section }}
          mark-complete: ${{ inputs.complete-on-merge }}
  move-to-in-review-asana-ticket-job:
    runs-on: ubuntu-latest
    needs: check-for-secrets
    if: inputs.review-section != '' && needs.check-for-secrets.outputs.has-asana-token == 'yes' && (github.event.action == 'review_requested' || github.event.action == 'ready_for_review' && (toJson(github.event.pull_request.requested_reviewers) != '[]' || toJson(github.event.pull_request.requested_teams) != '[]')) && !github.event.pull_request.draft && github.actor != 'dependabot[bot]'
    steps:
      - name: Move ticket on review requested
        uses:  mbta/github-asana-action@v4.4.2
        with:
          asana-pat: ${{ secrets.asana-token }}
          trigger-phrase: ${{ inputs.trigger-phrase }}
          target-section: ${{ inputs.review-section }}
  move-to-approved-asana-ticket-job:
    runs-on: ubuntu-latest
    needs: check-for-secrets
    if: inputs.approved-section != '' && needs.check-for-secrets.outputs.has-asana-token == 'yes' && github.event.action == 'submitted' && github.event.review.state == 'approved' && !github.event.pull_request.draft && github.actor != 'dependabot[bot]'
    steps:
      - name: Move ticket on approval
        uses:  mbta/github-asana-action@v4.4.2
        with:
          asana-pat: ${{ secrets.asana-token }}
          trigger-phrase: ${{ inputs.trigger-phrase }}
          target-section: ${{ inputs.approved-section }}
  create-asana-attachment-job:
    runs-on: ubuntu-latest
    needs: check-for-secrets
    name: Create pull request attachments on Asana tasks
    if: inputs.attach-pr && needs.check-for-secrets.outputs.has-github-secret == 'yes' && github.actor != 'dependabot[bot]'
    steps:
      - name: Create pull request attachments
        uses: Asana/create-app-attachment-github-action@v1.3
        id: postAttachment
        with:
          asana-secret: ${{ secrets.github-secret }}
        continue-on-error: true
      - name: Log output status
        run: echo "Status is ${{ steps.postAttachment.outputs.status }}"
