on:
  workflow_call:
    inputs:
      merged-section:
        type: string
        required: false
        description: The Asana project section for tickets with PRs that have been merged. Requires secrets.asana-token.
      review-section:
        type: string
        required: false
        description: The Asana project section for tickets with PRs that have a review requested. Requires secrets.asana-token.
      complete-on-merge:
        type: boolean
        default: false
        description: Whether to mark tasks for merged PRs as complete. Requires secrets.asana-token.
      attach-pr:
        type: boolean
        default: false
        description: Whether to attach the PR to the Asana ticket. Requires secrets.asana-github-secret.
      trigger-phrase:
        type: string
        default: "\\*\\*Asana Ticket:\\*\\*"
        description: Phrase to trigger moving ticket between columns.
    secrets:
      asana-token:
        required: false
        description: Asana personal access token that GitHub Actions uses to move ticket between sections.
      github-secret:
        required: false
        description: GitHub secret that Asana uses to fetch PR information.
jobs:
  check-for-secrets:
    runs-on: ubuntu-latest
    outputs:
      has-asana-token: ${{ secrets.asana-token != '' }}
      has-github-secret: ${{ secrets.github-secret != '' }}
    steps:
      - run: true
  move-to-merged-asana-ticket-job:
    runs-on: ubuntu-latest
    needs: check-for-secrets
    if: inputs.merged-section != '' && needs.check-for-secrets.output.has-asana-token == 'true' && github.event.pull_request.merged == true && github.actor != 'dependabot[bot]'
    steps:
      - name: Move ticket on merge
        uses:  mbta/github-asana-action@v4.3.0
        with:
          asana-pat: ${{ secrets.asana-token }}
          trigger-phrase: ${{ inputs.trigger-phrase }}
          target-section: ${{ inputs.merged-section }}
          mark-complete: ${{ inputs.complete-on-merge }}
  move-to-in-review-asana-ticket-job:
    runs-on: ubuntu-latest
    needs: check-for-secrets
    if: inputs.review-section != '' && needs.check-for-secrets.output.has-asana-token == 'true' && github.event.action == 'review_requested' && github.actor != 'dependabot[bot]'
    steps:
      - name: Move ticket on review requested
        uses:  mbta/github-asana-action@v4.3.0
        with:
          asana-pat: ${{ secrets.asana-token }}
          trigger-phrase: ${{ inputs.trigger-phrase }}
          target-section: ${{ inputs.review-section }}
  create-asana-attachment-job:
    runs-on: ubuntu-latest
    needs: check-for-secrets
    name: Create pull request attachments on Asana tasks
    if: inputs.attach-pr && needs.check-for-secrets.output.has-github-secret == 'true' && github.actor != 'dependabot[bot]'
    steps:
      - name: Create pull request attachments
        uses: Asana/create-app-attachment-github-action@v1.2
        id: postAttachment
        with:
          asana-secret: ${{ secrets.github-secret }}
      - name: Log output status
        run: echo "Status is ${{ steps.postAttachment.outputs.status }}"
